LitReview/LitReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from reviews.views import redirect_to_reviews_index

urlpatterns = [
    path('', redirect_to_reviews_index),
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LitReview/reviews/urls.py
from django.urls import path, include

from . import views

app_name = 'reviews'
urlpatterns = [
    path('', views.index, name='index'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('ticket_creation/', views.ticket_creation, name='ticket_creation'),
    path('ticket_response/', views.ticket_response, name='ticket_response'),
    path('review_creation/', views.review_creation, name='review_creation'),
    path('user_follows/', views.user_follows, name='user_follows'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.user_creation, name='signup'),
    path('delete_ticket/<int:pk>', views.TicketDeleteView.as_view(), name='delete_ticket'),
    path('delete_review/<int:pk>', views.ReviewDeleteView.as_view(), name='delete_review'),
    path('delete_follow/<int:pk>', views.UserFollowDeleteView.as_view(), name='delete_follow'),
]

LitReview/reviews/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models
from django.utils.translation import gettext as _

from django_resized import ResizedImageField


class Ticket(models.Model):
    """
    Ticket model class, child of Model django's generic class.
    Image is automatically resized using django_resized module.
    """
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=2048, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    image = ResizedImageField(size=[200, 300], quality=100, force_format='JPEG', null=True, blank=True, upload_to='book_covers')
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    """
    Review model class, child of Model django's generic class.
    Rating uses validators to ensure it is between 0 and 5.
    """
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline


class UserFollow(models.Model):
    """
    User follow model class, child of Model django's generic class.
    Subclass Meta ensures we don't get multiple UserFollows instances for unique user-user_followed pairs.
    """
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following'
    )
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by'
    )

    def __str__(self):
        return f"{self.user.username} abonné à {self.followed_user.username}"

    class Meta:
        unique_together = ('user', 'followed_user', )
        verbose_name = _("Abonné à un utilisateur")
        verbose_name_plural = _("Abonnés aux utilisateurs")

LitReview/reviews/forms.py
from django import forms


RATINGS = [('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]


class TicketResponseForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    headline = forms.CharField(label='Titre', max_length=128, widget=forms.TextInput(attrs={'size': '60'}))
    rating = forms.ChoiceField(label='Note', widget=forms.RadioSelect, choices=RATINGS)
    body = forms.CharField(label='Commentaire', max_length=8192, required=False, widget=forms.Textarea(attrs={'rows': '10', 'cols': '60'}))


class TicketCreationForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    title = forms.CharField(label='Titre', max_length=128, widget=forms.TextInput(attrs={'size': '60'}))
    description = forms.CharField(label='Description', max_length=2048, required=False, widget=forms.Textarea(attrs={'rows': '10', 'cols': '60'}))
    image = forms.ImageField(label='Image', required=False)


class ReviewCreationForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    title = forms.CharField(label='Titre', max_length=128, widget=forms.TextInput(attrs={'size': '60'}))
    description = forms.CharField(label='Description', max_length=2048, required=False, widget=forms.Textarea(attrs={'rows': '10', 'cols': '60'}))
    image = forms.ImageField(label='Image', required=False)
    headline = forms.CharField(label='Titre', max_length=128, widget=forms.TextInput(attrs={'size': '60'}))
    rating = forms.ChoiceField(label='Note', widget=forms.RadioSelect, choices=RATINGS)
    body = forms.CharField(label='Commentaire', max_length=8192, required=False,
                           widget=forms.Textarea(attrs={'rows': '10', 'cols': '60'}))


class UserSearchForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    username_searched = forms.CharField(label='', max_length=150, widget=forms.TextInput(attrs={'size': '60'}))

LitReview/reviews/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib import messages
from itertools import chain

from .forms import TicketResponseForm, TicketCreationForm, ReviewCreationForm, UserSearchForm
from .models import Review, Ticket, UserFollow


def redirect_to_reviews_index(request):
    """
    Simple view used in urls.py to redirect from root to reviews app index.
    :param request:
    :return: Redirection to reviews' index.
    """
    return redirect('reviews:index')


@login_required(login_url='reviews:login')
def index(request):
    """
    This index view finds tickets and reviews from followed users and actual users.
    Merges them and sort them the most recent first.
    :param request:
    :return: A render of the index page using it's template.
    """
    tickets = Ticket.objects.filter(user=request.user)
    reviews = Review.objects.filter(user=request.user)

    followings = UserFollow.objects.filter(user=request.user)
    for following in followings:
        tickets = tickets | Ticket.objects.filter(user=following.followed_user)
        reviews = reviews | Review.objects.filter(user=following.followed_user)

    tickets_and_reviews = sorted(
        chain(tickets, reviews),
        key=lambda x: x.time_created, reverse=True)
    star_count = [0, 1, 2, 3, 4]
    context = {
        'tickets_and_reviews': tickets_and_reviews,
        'star_count': star_count
    }
    return render(request, 'reviews/index.html', context)


@login_required(login_url='reviews:login')
def my_posts(request):
    """
    This index view finds tickets and reviews from actual users.
    Merges them and sort them the most recent first.
    It also handles deletion and modification of tickets and reviews.
    :param request:
    :return: A render of the index page using it's template.
    """
    star_count = [0, 1, 2, 3, 4]
    if request.method == 'POST':
        if request.POST.get('role') == 'delete':
            if request.POST.get('review_id'):
                return redirect(f"/reviews/delete_review/{request.POST.get('review_id')}")
            elif request.POST.get('ticket_id'):
                return redirect(f"/reviews/delete_ticket/{request.POST.get('ticket_id')}")

        elif request.POST.get('role') == 'modify':
            # checking 'review_id' presence first to recognize if it is a review,
            # because both reviews and tickets POSTs returns a 'ticket_id' attribute
            if request.POST.get('review_id'):
                review = get_object_or_404(Review, pk=request.POST.get('review_id'))
                ticket = get_object_or_404(Ticket, pk=request.POST.get('ticket_id'))
                data = {
                    'headline': review.headline,
                    'rating': review.rating,
                    'body': review.body
                }
                form = TicketResponseForm(initial=data)
                context = {
                    'review': review,
                    'ticket': ticket,
                    'form': form,
                    'role': 'modify',
                }
                return render(request, 'reviews/ticket_response.html', context)

            elif request.POST.get('ticket_id'):
                ticket = get_object_or_404(Ticket, pk=request.POST.get('ticket_id'))
                data = {
                    'title': ticket.title,
                    'description': ticket.description,
                    'image': ticket.image
                }
                form = TicketCreationForm(initial=data)

                context = {
                    'form': form,
                    'ticket': ticket,
                }
                return render(request, 'reviews/ticket_creation.html', context)

    tickets = Ticket.objects.filter(user=request.user)
    reviews = Review.objects.filter(user=request.user)

    tickets_and_reviews = sorted(
        chain(tickets, reviews),
        key=lambda x: x.time_created, reverse=True)
    context = {
        'tickets_and_reviews': tickets_and_reviews,
        'star_count': star_count
    }
    return render(request, 'reviews/my_posts.html', context)


@login_required(login_url='reviews:login')
def ticket_creation(request):
    """
    View to modify or create a new ticket.
    :param request:
    :return: A redirection to my_posts if the ticket is modified,
        a redirection to feed page if the ticket is created,
        or a render of it's template with a blank form if user wants to create a new ticket.
    """
    if request.method == 'POST':
        form = TicketCreationForm(request.POST, request.FILES)
        if form.is_valid():
            if request.POST.get('ticket_id'):
                ticket = get_object_or_404(Ticket, pk=request.POST.get('ticket_id'))
                ticket.title = form.cleaned_data['title']
                ticket.description = form.cleaned_data['description']
                ticket.image = form.cleaned_data['image']
                ticket.save()
                messages.success(request, f'Votre ticket "{ticket.title}" a bien été modifié.')
                return redirect('/reviews/my_posts')
            else:
                ticket = Ticket(
                    title=form.cleaned_data['title'],
                    description=form.cleaned_data['description'],
                    image=form.cleaned_data['image'],
                    user=request.user
                )
                ticket.save()
                messages.success(request, f'Votre ticket "{ticket.title}" a bien été créé.')
                return redirect('/reviews/')
    else:
        form = TicketCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'reviews/ticket_creation.html', context)


@login_required(login_url='reviews:login')
def ticket_response(request):
    """
    View to modify or create a review in response to an existing ticket.
    :param request:
    :return: A redirection to my_posts if the review is modified,
        a redirection to feed page if the review is created,
        or a render of it's template with a blank form if user wants to create a new review.
    """
    if request.method == 'POST':
        form = TicketResponseForm(request.POST)
        if form.is_valid():
            if request.POST.get('review_id'):
                review = get_object_or_404(Review, pk=request.POST.get('review_id'))
                review.headline = form.cleaned_data['headline']
                review.rating = form.cleaned_data['rating']
                review.body = form.cleaned_data['body']
                review.save()
                messages.success(request, f'Votre critique "{review.headline}" a bien été modifiée.')
                return redirect('/reviews/my_posts')
            else:
                review = Review(
                    headline=form.cleaned_data['headline'],
                    rating=form.cleaned_data['rating'],
                    body=form.cleaned_data['body'],
                    ticket=get_object_or_404(Ticket, pk=request.POST.get('ticket_id')),
                    user=request.user
                )
                review.save()
                messages.success(request, f'Votre critique "{review.headline}" a bien été créée.')
                return redirect('/reviews/')
    else:
        form = TicketResponseForm()

    ticket = get_object_or_404(Ticket, pk=request.POST.get('ticket_id'))
    context = {
        'ticket': ticket,
        'form': form,
    }
    return render(request, 'reviews/ticket_response.html', context)


@login_required(login_url='reviews:login')
def review_creation(request):
    """
    View to create a ticket and it's review at the same time.
    :param request:
    :return: A redirection to feed page if the ticket and review is created,
        or a render of it's template with a blank form if user wants to create a new ticket and review.
    """
    if request.method == 'POST':
        form = ReviewCreationForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = Ticket(
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                image=form.cleaned_data.get('image'),
                user=request.user
            )
            ticket.save()

            review = Review(
                headline=form.cleaned_data['headline'],
                rating=form.cleaned_data['rating'],
                body=form.cleaned_data['body'],
                ticket=ticket,
                user=request.user
            )
            review.save()

            messages.success(request, f'Votre critique "{review.headline}" a bien été créée.')
            return redirect('/reviews/')
    else:
        form = ReviewCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'reviews/review_creation.html', context)


@login_required(login_url='reviews:login')
def user_follows(request):
    """
    View to show user's follows and followers, to search and add new follows, or to delete existing follows.
    :param request:
    :return: A render of it's template with the search, add or delete form, or a blank form.
    """
    form = UserSearchForm()
    search_matches = []
    if request.method == 'POST':
        if request.POST.get('role') == 'search':
            form = UserSearchForm(request.POST)
            if form.is_valid():
                username_searched = form.cleaned_data['username_searched']
                if User.objects.filter(username=username_searched):

LitReview/reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>LIT Review</title>
        <link rel="Shortcut icon" type="image/gif" href="{% static 'reviews/assets/favicon.gif' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Star icon library-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'reviews/css/styles.css' %}" rel="stylesheet" />
        <!-- Additional CSS-->
        <link href="{% static 'reviews/css/components.css' %}" rel="stylesheet" />
        {% block css %}{% endblock %}
    </head>
        <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">Ici on aime les livres !</span>
                <span class="site-heading-lower">LIT Review</span>
            </h1>
        </header>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="index.html">LIT Review</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'reviews:index' %}">Flux</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'reviews:my_posts' %}">Mes posts</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'reviews:user_follows' %}">Abonnements</a></li>
                        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'reviews:logout' %}">Se déconnecter du compte {{ request.user }}</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {%block content %}{% endblock %}

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; LIT Review 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
<!--        <script src="{% static 'reviews/js/scripts.js' %}"></script>-->
        {% block extra_js %}{% endblock %}
    </body>
</html>

LitReview/reviews/templates/reviews/index.html
{% extends 'reviews/base.html' %}
{% block content %}
    <section class="page-section cta text-center">
            <a href="{% url 'reviews:ticket_creation' %}"><button class="btn btn-warning">Demander une critique</button></a>
            <a href="{% url 'reviews:review_creation' %}"><button class="btn btn-warning">Créer une critique</button></a>
        </br>
        </br>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    {% if messages %}
                        </br>
                        {% for message in messages %}
                            {% if message.tags == "error" %}
                                <div class="alert alert-danger" role="alert">
                                    <h2 class="{{ message.tags }}">{{ message }}</h2>
                                </div>
                            {% else %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    <h2 class="{{ message.tags }}">{{ message }}</h2>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% for ticket_or_review in tickets_and_reviews %}
                        {% if ticket_or_review.title %}
                            {% include 'reviews/ticket.html' with ticket=ticket_or_review %}
                        {% else %}
                            {% include 'reviews/review.html' with review=ticket_or_review %}
                        {% endif %}
                    {% empty %}
                    <h2>Pas de critique à afficher, abonnez-vous à des utilisateurs pour voir leurs critiques !</h2>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

LitReview/reviews/templates/reviews/my_posts.html
{% extends 'reviews/base.html' %}
{% block content %}
    <section class="page-section cta text-center">
        <h1>Vos posts</h1>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    {% if messages %}
                        </br>
                        {% for message in messages %}
                            {% if message.tags == "error" %}
                                <div class="alert alert-danger" role="alert">
                                    <h2 class="{{ message.tags }}">{{ message }}</h2>
                                </div>
                            {% else %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    <h2 class="{{ message.tags }}">{{ message }}</h2>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% for ticket_or_review in tickets_and_reviews %}
                        {% if ticket_or_review.title %}
                            {% include 'reviews/ticket.html' with ticket=ticket_or_review %}
                        {% else %}
                            {% include 'reviews/review.html' with review=ticket_or_review %}
                        {% endif %}
                    {% empty %}
                        <hr>
                        <h2>Vous n'avez encore rien posté...</h2>
                        </br>
                        </br>
                        <a href="{% url 'reviews:ticket_creation' %}"><button class="btn btn-warning">Demander une critique</button></a>
                        <a href="{% url 'reviews:review_creation' %}"><button class="btn btn-warning">Créer une critique</button></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

LitReview/reviews/templates/reviews/review_confirm_delete.html
{% extends 'reviews/base.html' %}
{% block content %}
<div class="cta-inner bg-faded text-center rounded">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                </br>
                <form method="post">{% csrf_token %}
                    <h2>Êtes vous sûr de vouloir supprimer votre critique : "{{ object }}" ?</h2>
                    <button class="btn btn-danger" type="submit" value="Confirm">Confirmer</button>
                </form>
                <a href="{% url 'reviews:my_posts' %}"><button class="btn btn-warning">Annuler</button></a>
                </br>
                </br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

LitReview/reviews/templates/reviews/review_creation.html
{% extends 'reviews/base.html' %}
{% block content %}
    </br>
    <section class="page-section cta text-center">
        <h2>Créer une critique</h2>
        </br>
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    {% include 'reviews/review_creation_form.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

LitReview/reviews/templates/reviews/review_creation_form.html
<form class="form" action="{% url 'reviews:review_creation' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {% if forloop.counter == 1 %}
                <div class="cta-inner bg-faded text-center rounded">
                    <h2>Livre / Article</h2>
            {% endif %}
            {% if forloop.counter == 4 %}
                <div class="cta-inner bg-faded text-center rounded">
                    <h2>Critique</h2>
            {% endif %}
                    <div class="formField">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        </br>
                        {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    </br>
            {% if forloop.counter == 3 %}
                </div>
            {% endif %}
        {% endfor %}
                    <button class="btn btn-success" type="submit" class="">Envoyer</button>
                </div>
</form>

LitReview/reviews/templates/reviews/ticket.html
<div class="cta-inner bg-faded text-center rounded">
    <h2 class="section-heading mb-4">
        {% if request.user == ticket.user %}
            <span class="section-heading-upper">Votre demande de critique du {{ ticket.time_created }}</span>
        {% else %}
            <span class="section-heading-upper">Demande de critique de {{ ticket.user }} du {{ ticket.time_created }}</span>
        {% endif %}
        <span class="section-heading-lower">{{ ticket.title }}</span>
    </h2>
    <p class="mb-0">{{ ticket.description }}</p>
    </br>
    {% if ticket.image %}
        <p>
            <img src="{{ ticket.image.url }}" alt="" height="300">
        </p>
    {% endif %}
    {% if request.get_full_path == '/reviews/' %}
        {% if ticket.review_set.count == 0 %}
            <form class="form" action="{% url 'reviews:ticket_response' %}" method="post">
                {% csrf_token %}
                <input type="hidden" class="hidden" value="{{ ticket.id }}" name="ticket_id">
                <button class="btn btn-warning" type="submit">Soumettre une critique</button>
            </form>
        {% endif %}
    {% endif %}

    {% if request.get_full_path == '/reviews/my_posts/' and role != 'modify' %}
        <form class="form" action="{% url 'reviews:my_posts' %}" method="post">
            {% csrf_token %}
            <input type="hidden" class="hidden" value="{{ ticket.id }}" name="ticket_id">
            <input type="hidden" class="hidden" value="modify" name="role">
            <button class="btn btn-warning" type="submit">Modifier</button>
        </form>

        <form class="form" action="{% url 'reviews:my_posts' %}" method="post">
            {% csrf_token %}
            <input type="hidden" class="hidden" value="{{ ticket.id }}" name="ticket_id">
            <input type="hidden" class="hidden" value="delete" name="role">
            <button class="btn btn-danger" type="submit">Supprimer</button>
        </form>
    {% endif %}
</div>

LitReview/reviews/templates/reviews/ticket_confirm_delete.html
{% extends 'reviews/base.html' %}
{% block content %}
<div class="cta-inner bg-faded text-center rounded">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                </br>
                <form method="post">{% csrf_token %}
                    <h2>Êtes vous sûr de vouloir supprimer votre ticket : "{{ object }}" ?</h2>
                    <button class="btn btn-danger" type="submit" value="Confirm">Confirmer</button>
                </form>
                 <a href="{% url 'reviews:my_posts' %}"><button class="btn btn-warning">Annuler</button></a>
                </br>
                </br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

LitReview/reviews/templates/reviews/ticket_creation_form.html
<div class="cta-inner bg-faded text-center rounded">
    <form class="form" action="{% url 'reviews:ticket_creation' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" class="hidden" value="{{ ticket.id }}" name="ticket_id">
        {% for field in form %}
                <div class="formField">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    </br>
                    <p>
                        {% if field.label == "Image" and ticket.image %}
                            <img src="{{ ticket.image.url }}" alt="" width="100">
                        {% endif %}
                        {{ field }}
                    </p>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                </br>
        {% endfor %}
        <button class="btn btn-success" type="submit" class="">Envoyer</button>
    </form>
</div>

LitReview/reviews/templates/reviews/ticket_response_form.html
<h2>Vous êtes en train de poster en réponse à :</h2>
{% include 'reviews/ticket.html' with ticket=ticket %}
</br>
<h2>Votre critique :</h2>
<div class="cta-inner bg-faded text-center rounded">
    <form class="form" action="{% url 'reviews:ticket_response' %}" method="post">
        {% csrf_token %}
        <input type="hidden" class="hidden" value="{{ ticket.id }}" name="ticket_id">
        <input type="hidden" class="hidden" value="{{ review.id }}" name="review_id">
        {% for field in form %}
                <div class="formField">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    </br>
                    {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                </br>
        {% endfor %}
        <button class="btn btn-success" type="submit" class="">Envoyer</button>
    </form>
</div>

LitReview/reviews/templates/reviews/userfollow_confirm_delete.html
{% extends 'reviews/base.html' %}
{% block content %}
<div class="cta-inner bg-faded text-center rounded">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                </br>
                <form method="post">{% csrf_token %}
                    <h2>Êtes vous sûr de vouloir supprimer votre abonnement à {{ object.followed_user }} ?</h2>
                    <button class="btn btn-danger" type="submit" value="Confirm">Confirmer</button>
                </form>
                <a href="{% url 'reviews:user_follows' %}"><button class="btn btn-warning">Annuler</button></a>
                </br>
                </br>
            </div>
        </div>
    </div>
</div>
{% endblock %}